#!/usr/bin/env python3
"""
Co-Founder Strategy Session generator for MadTech Growth.

Runs weekly (Friday 4-5 PM) to:
- Read biz_state.json for pipeline health
- Check Cron Outputs/ for recent activity
- Generate strategic insight, experiment, risk, and question for Scott
- Write Strategy Sessions/YYYY-MM-DD-strategy.md
"""

import json
from datetime import date, datetime
from pathlib import Path

BIZ_STATE_PATH = Path.home() / "Desktop" / "ScottOS" / "Business State" / "biz_state.json"
CRON_OUTPUTS_DIR = Path.home() / "Desktop" / "ScottOS" / "Cron Outputs"
STRATEGY_DIR = Path.home() / "Desktop" / "ScottOS" / "Strategy Sessions"

def load_state():
    with open(BIZ_STATE_PATH) as f:
        return json.load(f)

def get_last_snapshot_date():
    files = sorted(CRON_OUTPUTS_DIR.glob("geo_content_brief_*.md"))
    if files:
        latest = files[-1]
        mtime = datetime.fromtimestamp(latest.stat().st_mtime).date()
        return mtime.isoformat()
    return None

def generate_strategy_insight(state, last_snapshot):
    health = state.get("pipeline_health", "unknown")
    if health == "critical":
        return "Pipeline is critically dry — immediate revenue-generating activity is the only priority. Framework refinement, tooling, and optimization are off-limits until pipeline shows movement."
    elif health == "stalled":
        return "Pipeline momentum has stalled. Consider refreshing outreach messaging and expanding beyond law firms into DTC/eCommerce where buying cycles may be faster."
    elif health == "active":
        return "Good momentum. Now is the time to refine the discovery call flow and audit proposal based on real prospect feedback — not hypotheticals."
    else:
        return "Establish baseline metrics and track them weekly. Data beats opinion every time."

def generate_experiment(state):
    return {
        "hypothesis": "If we send 5 snapshots per week minimum, then discovery calls will increase to 2+/week within 30 days.",
        "metric": "Discovery calls booked per week (track in biz_state.json)",
        "duration": "4 weeks"
    }

def generate_risk(state):
    contacted = state.get("prospects", {}).get("contacted_this_month", 0)
    if contacted < 5:
        return "Single point of failure: Scott is the only outreach engine. Risk: W-2 workload spike kills pipeline. Mitigation: Build repeatable prospect target list and email sequences so outreach survives busy weeks."
    return "No clients yet means credibility is still building. Mitigation: Ship first audit quickly, get case study, use it to break into DTC vertical."

def generate_question():
    return "Should we pivot to targeting DTC/eCommerce sooner rather than later, given law firm outreach cycle appears slower than expected?"

def write_session(insight, experiment, risk, question, state):
    today = date.today().isoformat()
    session_file = STRATEGY_DIR / f"{today}-strategy.md"
    
    content = f"""# Strategy Session — {today}

## Pipeline Health
- Pipeline status: {state.get('pipeline_health', 'unknown')}
- Last snapshot sent: {state.get('last_snapshot_sent', 'none recorded')}
- Prospects contacted this month: {state.get('prospects', {}).get('contacted_this_month', 0)}
- Discovery calls scheduled: {state.get('prospects', {}).get('discovery_scheduled', 0)}
- Pipeline value: ${state.get('pipeline_value_usd', 0):,}

## Key Insight
{insight}

## Next Week's Experiment
**Hypothesis:** {experiment['hypothesis']}
**Metric:** {experiment['metric']}
**Timebox:** {experiment['duration']}

## Risk Identified
{risk}

## Question for Scott
{question}

---
*Generated by Hermes Co-Founder Strategy Agent*
"""
    
    with open(session_file, 'w') as f:
        f.write(content)
    return session_file

def main():
    state = load_state()
    last_snapshot = get_last_snapshot_date()
    
    insight = generate_strategy_insight(state, last_snapshot)
    experiment = generate_experiment(state)
    risk = generate_risk(state)
    question = generate_question()
    
    session_path = write_session(insight, experiment, risk, question, state)
    print(f"Strategy session written: {session_path}")
    print("\n--- Summary ---")
    print(f"Pipeline health: {state.get('pipeline_health')}")
    print(f"Insight: {insight[:80]}...")
    print(f"Risk: {risk[:80]}...")

if __name__ == "__main__":
    main()
