"""
Daily Lead Report — Human-readable markdown digest of all discovered prospects.

Writes a single file: reports/daily_leads_YYYY-MM-DD.md
This is the canonical "morning review sheet" for Scott.
"""

from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from shared.base import Prospect


def priority_emoji(priority: str) -> str:
    return {"hot": "🔥", "warm": "🟡", "cold": "🔵"}.get(priority.lower(), "⚪")


def score_badge(score: float) -> str:
    if score >= 0.8:
        return f"**{score:.2f}** 🔥"
    elif score >= 0.5:
        return f"{score:.2f} 🟡"
    return f"{score:.2f} 🔵"


def write_daily_report(
    prospects: list["Prospect"],
    md_paths: Optional[list[Path]] = None,
    pdf_paths: Optional[list[Path]] = None,
    reports_dir: Optional[Path] = None,
) -> Path:
    """
    Write a human-readable daily lead report to reports/daily_leads_YYYY-MM-DD.md

    Args:
        prospects: All prospects discovered today
        md_paths: Optional list of generated markdown snapshot paths
        pdf_paths: Optional list of generated PDF snapshot paths
        reports_dir: Directory to write report (default: project_root/reports)

    Returns:
        Path to the written markdown file
    """
    if reports_dir is None:
        reports_dir = Path(__file__).parent.parent / "reports"
    reports_dir.mkdir(exist_ok=True)

    today = date.today()
    md_path = reports_dir / f"daily_leads_{today.isoformat()}.md"

    # Build lookup: domain -> {md, pdf}
    md_by_domain: dict[str, Path] = {}
    if md_paths:
        for p in md_paths:
            domain = p.stem.replace("geo_snapshot_", "").replace(f"_{today.isoformat()}", "")
            md_by_domain[domain] = p

    pdf_by_domain: dict[str, Path] = {}
    if pdf_paths:
        for p in pdf_paths:
            domain = p.stem.replace("geo_snapshot_", "").replace(f"_{today.isoformat()}", "")
            pdf_by_domain[domain] = p

    # Sort by normalized score descending
    ranked = sorted(prospects, key=lambda p: p.normalized_score, reverse=True)

    hot = [p for p in ranked if p.normalized_score >= 0.8]
    warm = [p for p in ranked if 0.5 <= p.normalized_score < 0.8]
    cold = [p for p in ranked if p.normalized_score < 0.5]

    lines: list[str] = [
        f"# Daily GEO Lead Report — {today.strftime('%B %d, %Y')}",
        "",
        "**MadTech Growth — GEO Discovery Pipeline**",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| **Total Leads** | {len(ranked)} |",
        f"| 🔥 Hot (≥0.8) | {len(hot)} |",
        f"| 🟡 Warm (0.5–0.79) | {len(warm)} |",
        f"| 🔵 Cold (<0.5) | {len(cold)} |",
        f"| 📄 Snapshots Ready | {len(md_by_domain)} |",
        "",
    ]

    if hot:
        lines.extend([
            "## 🔥 Hot Leads (Action Required)",
            "",
        ])
        for p in hot:
            lines.extend(_prospect_section(p, md_by_domain, pdf_by_domain))

    if warm:
        lines.extend([
            "## 🟡 Warm Leads",
            "",
        ])
        for p in warm:
            lines.extend(_prospect_section(p, md_by_domain, pdf_by_domain))

    if cold:
        lines.extend([
            "## 🔵 Cold Leads",
            "",
        ])
        for p in cold:
            lines.extend(_prospect_section(p, md_by_domain, pdf_by_domain))

    # Master table at the bottom for quick scanning
    lines.extend([
        "---",
        "",
        "## Quick Reference Table",
        "",
        "| Priority | Company | URL | Vertical | Score | Top Gap | Snapshot? |",
        "|----------|---------|-----|----------|-------|---------|-----------|",
    ])
    for p in ranked:
        pri_emoji = "🔥" if p.normalized_score >= 0.8 else "🟡" if p.normalized_score >= 0.5 else "🔵"
        name = p.name or "Unknown"
        url_short = p.url.replace("https://", "").replace("http://", "")[:35]
        vert = p.vertical.upper() if p.vertical else "—"
        score = f"{p.normalized_score:.2f}"
        top_gap = (p.geo_gaps[0] if p.geo_gaps else "—")[:40]
        domain_key = p.url.replace("https://", "").replace("http://", "").replace("www.", "").split("/")[0].replace(".", "_")
        has_snapshot = "✅" if any(domain_key in str(k) for k in md_by_domain.keys()) else "—"
        lines.append(f"| {pri_emoji} | {name} | [{url_short}]({p.url}) | {vert} | {score} | {top_gap} | {has_snapshot} |")

    lines.extend([
        "",
        "---",
        "",
        "*To generate a full PDF snapshot for any lead, run:*",
        "```bash",
        "python3 generate_geo_report.py <URL> --pdf",
        "```",
        "",
        f"*Report generated by MadTech Growth GEO Agent · {today.isoformat()}*",
    ])

    md_path.write_text("\n".join(lines), encoding="utf-8")
    return md_path


def _prospect_section(p: "Prospect", md_by_domain: dict[str, Path], pdf_by_domain: dict[str, Path]) -> list[str]:
    """Generate a detail section for a single prospect."""
    domain_key = p.url.replace("https://", "").replace("http://", "").replace("www.", "").split("/")[0].replace(".", "_")
    md_link = ""
    for k, v in md_by_domain.items():
        if domain_key in k or k in domain_key:
            md_link = f"\n  - 📄 [Snapshot MD]({v})"
            break
    pdf_link = ""
    for k, v in pdf_by_domain.items():
        if domain_key in k or k in domain_key:
            pdf_link = f"\n  - 📎 [Snapshot PDF]({v})"
            break

    gaps = "\n".join(f"  - {g}" for g in (p.geo_gaps[:3] or ["No gaps identified"]))
    contacts = []
    if p.emails:
        contacts.append(f"  - 📧 {', '.join(p.emails[:2])}")
    if p.phones:
        contacts.append(f"  - 📞 {', '.join(p.phones[:2])}")
    if p.linkedin:
        contacts.append(f"  - 💼 [LinkedIn]({p.linkedin})")
    contacts_md = "\n".join(contacts) if contacts else "  - No contacts found"

    return [
        f"### {p.name or 'Unknown'} — {p.category or 'Unknown Category'}",
        "",
        f"- **URL:** [{p.url}]({p.url})",
        f"- **Vertical:** {p.vertical.upper() if p.vertical else '—'}",
        f"- **Location:** {p.location or '—'}",
        f"- **GEO Score:** {p.normalized_score:.2f} / 1.0 (raw: {p.raw_score}/{p.max_score})",
        f"- **Priority:** {'🔥 Hot' if p.normalized_score >= 0.8 else '🟡 Warm' if p.normalized_score >= 0.5 else '🔵 Cold'}",
        f"- **Recommended Action:** {p.recommended_action or '—'}",
        f"{md_link}",
        f"{pdf_link}",
        "",
        "**Top Gaps:**",
        f"{gaps}",
        "",
        "**Contacts:**",
        f"{contacts_md}",
        "",
        "---",
        "",
    ]
